#!/usr/bin/env python3
"""Search for fully locked C5 cells outside the known quotient component.

The model jointly encodes a strict quadratic representative and ten gated
nonnegative Fourier-moment duals.  It excludes every raw order-40 symmetry
image of the component generated by survey_n5_c5_locked_cells.py.

This is a numerical MILP search.  A feasible mask is rechecked by ten LPs and
is a valid seed for another component.  Infeasibility is not, by itself, an
exact completeness certificate.
"""

from __future__ import annotations

import argparse

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, milp
from scipy.sparse import coo_matrix

import screen_n5_c5_two_scale as c5
import survey_n5_c5_locked_cells as survey


def component_orbit_masks(component: dict[int, np.ndarray]) -> set[int]:
    answer = set()
    for mask in component:
        for permutation, exchanges_colors in survey.fixed_orthant_symmetries():
            image = survey.permute_mask(mask, permutation)
            if exchanges_colors:
                image = survey.FULL_MASK ^ image
            answer.add(int(image))
            answer.add(int(survey.global_input_complement(image)))
    return answer


def append(
    row_indices: list[int],
    column_indices: list[int],
    data: list[float],
    row: int,
    column: int,
    value: float,
) -> None:
    row_indices.append(row)
    column_indices.append(column)
    data.append(float(value))


def build_model(
    excluded_masks: set[int],
    coefficient_bound: float,
    dual_bound: float,
    symmetry_break: bool,
) -> tuple[np.ndarray, np.ndarray, Bounds, LinearConstraint, dict[str, int]]:
    vertices = 32
    dimension = 16
    edge_count = 10
    truth_start = 0
    coefficient_start = vertices
    dual_start = coefficient_start + dimension
    variable_count = dual_start + edge_count * 2 * vertices

    objective = np.zeros(variable_count)
    integrality = np.zeros(variable_count, dtype=np.uint8)
    integrality[:vertices] = 1
    lower = np.zeros(variable_count)
    upper = np.ones(variable_count)
    lower[coefficient_start:dual_start] = -coefficient_bound
    upper[coefficient_start:dual_start] = coefficient_bound
    if not symmetry_break:
        upper[0] = 0.0
    upper[dual_start:] = dual_bound

    row_indices: list[int] = []
    column_indices: list[int] = []
    data: list[float] = []
    constraint_lower: list[float] = []
    constraint_upper: list[float] = []
    row = 0
    fourier = c5.FOURIER.astype(np.int64)

    big_m = 16 * coefficient_bound + 1
    for vertex in range(vertices):
        append(row_indices, column_indices, data, row, truth_start + vertex, -big_m)
        for column, value in enumerate(fourier[vertex]):
            append(
                row_indices,
                column_indices,
                data,
                row,
                coefficient_start + column,
                value,
            )
        constraint_lower.append(1 - big_m)
        constraint_upper.append(-1)
        row += 1

    for edge_index, edge_sign in enumerate(c5.EDGE_SIGNS.astype(np.int64)):
        append(
            row_indices,
            column_indices,
            data,
            row,
            coefficient_start + 6 + edge_index,
            edge_sign,
        )
        constraint_lower.append(1)
        constraint_upper.append(np.inf)
        row += 1

    for edge_index, edge_sign in enumerate(c5.EDGE_SIGNS.astype(np.int64)):
        positive = dual_start + edge_index * 2 * vertices
        negative = positive + vertices
        for feature in range(dimension):
            for vertex in range(vertices):
                value = fourier[vertex, feature]
                append(
                    row_indices,
                    column_indices,
                    data,
                    row,
                    positive + vertex,
                    value,
                )
                append(
                    row_indices,
                    column_indices,
                    data,
                    row,
                    negative + vertex,
                    -value,
                )
            target = int(edge_sign) if feature == 6 + edge_index else 0
            constraint_lower.append(target)
            constraint_upper.append(target)
            row += 1
        for vertex in range(vertices):
            append(row_indices, column_indices, data, row, positive + vertex, 1)
            append(
                row_indices,
                column_indices,
                data,
                row,
                truth_start + vertex,
                -dual_bound,
            )
            constraint_lower.append(-np.inf)
            constraint_upper.append(0)
            row += 1

            append(row_indices, column_indices, data, row, negative + vertex, 1)
            append(
                row_indices,
                column_indices,
                data,
                row,
                truth_start + vertex,
                dual_bound,
            )
            constraint_lower.append(-np.inf)
            constraint_upper.append(dual_bound)
            row += 1

    for mask in sorted(excluded_masks):
        positive_count = bin(mask).count("1")
        for vertex in range(vertices):
            coefficient = -1 if (mask >> vertex) & 1 else 1
            append(
                row_indices,
                column_indices,
                data,
                row,
                truth_start + vertex,
                coefficient,
            )
        constraint_lower.append(1 - positive_count)
        constraint_upper.append(np.inf)
        row += 1

    if symmetry_break:
        vertex_weights = [1 << vertex for vertex in range(vertices)]
        full_weight = (1 << vertices) - 1
        seen_transformations = set()
        for permutation, exchanges_colors in survey.fixed_orthant_symmetries():
            for input_complement in (False, True):
                targets = []
                for vertex in range(vertices):
                    image = 0
                    for source, target in enumerate(permutation):
                        image |= ((vertex >> source) & 1) << target
                    if input_complement:
                        image ^= vertices - 1
                    targets.append(image)
                key = (tuple(targets), exchanges_colors)
                if key in seen_transformations:
                    continue
                seen_transformations.add(key)
                if targets == list(range(vertices)) and not exchanges_colors:
                    continue
                for vertex, target in enumerate(targets):
                    if exchanges_colors:
                        coefficient = vertex_weights[vertex] + vertex_weights[target]
                    else:
                        coefficient = vertex_weights[vertex] - vertex_weights[target]
                    if coefficient:
                        append(
                            row_indices,
                            column_indices,
                            data,
                            row,
                            truth_start + vertex,
                            coefficient,
                        )
                constraint_lower.append(-np.inf)
                constraint_upper.append(full_weight if exchanges_colors else 0)
                row += 1
        assert len(seen_transformations) == 40

    matrix = coo_matrix(
        (data, (row_indices, column_indices)),
        shape=(row, variable_count),
    ).tocsr()
    metadata = {
        "variables": variable_count,
        "binary_variables": vertices,
        "constraints": row,
        "nonzeros": matrix.nnz,
        "excluded_masks": len(excluded_masks),
        "coefficient_start": coefficient_start,
        "symmetry_break": int(symmetry_break),
    }
    return (
        objective,
        integrality,
        Bounds(lower, upper),
        LinearConstraint(
            matrix,
            np.array(constraint_lower),
            np.array(constraint_upper),
        ),
        metadata,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--component-limit", type=int, default=1000)
    parser.add_argument(
        "--extra-seed",
        type=lambda value: int(value, 0),
        action="append",
        default=[],
    )
    parser.add_argument("--coefficient-bound", type=float, default=10_000)
    parser.add_argument("--dual-bound", type=float, default=1_000)
    parser.add_argument("--time-limit", type=float, default=300)
    parser.add_argument("--no-symmetry-break", action="store_true")
    arguments = parser.parse_args()

    component, exhausted = survey.locked_class_walk(arguments.component_limit)
    assert exhausted
    known_components = [component]
    for seed in arguments.extra_seed:
        extra, exhausted = survey.locked_class_walk_from_mask(
            seed, arguments.component_limit
        )
        assert exhausted
        assert not set(extra).intersection(component)
        known_components.append(extra)
        component.update(extra)
    symmetry_break = not arguments.no_symmetry_break
    excluded = set(component) if symmetry_break else component_orbit_masks(component)
    objective, integrality, bounds, constraints, metadata = build_model(
        excluded,
        arguments.coefficient_bound,
        arguments.dual_bound,
        symmetry_break,
    )
    print(f"known locked components: {len(known_components)}", flush=True)
    print(f"known quotient component classes: {len(component)}", flush=True)
    print(f"MILP metadata: {metadata}", flush=True)
    result = milp(
        objective,
        integrality=integrality,
        bounds=bounds,
        constraints=constraints,
        options={
            "time_limit": arguments.time_limit,
            "mip_rel_gap": 0.0,
            "presolve": True,
        },
    )
    print(f"MILP status: {result.status}", flush=True)
    print(f"MILP message: {result.message}", flush=True)
    if result.x is None:
        print("warning: numerical infeasibility is not an exact certificate")
        return

    mask = sum(
        (int(round(result.x[vertex])) > 0) << vertex for vertex in range(32)
    )
    canonical = survey.canonical_mask(mask)
    signs = np.array(
        [1 if (mask >> vertex) & 1 else -1 for vertex in range(32)],
        dtype=float,
    )
    assert canonical not in component
    assert survey.fully_locked(signs)
    coefficients = result.x[
        metadata["coefficient_start"] : metadata["coefficient_start"] + 16
    ]
    assert np.min(signs * (c5.FOURIER @ coefficients)) > 0.9
    print(f"new locked seed mask: 0x{mask:08x}")
    print(f"new locked canonical mask: 0x{canonical:08x}")


if __name__ == "__main__":
    main()
